{% set name = "pyimapsync" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyimapsync-{{ version }}.tar.gz
  sha256: fe4f7244fdc83faba005065ab0347474393b9817bf0d641f425574b5588846af

build:
  entry_points:
    - pyimapsync=pyimapsync.__main__:command_line_parser
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyimapsync
  commands:
    - pip check
    - pyimapsync --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyscioffice/pyimapsync
  summary: Transfer emails between multiple IMAP servers.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
